sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - hi@manta.life
    on_success: never
    on_failure: always
script:
  - yarn run test
  - yarn run release
deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
